### ISSUE TITLE
Add required fields

### ISSUE THREAD

**Issue by RoRoche** [jenzz/Java-PojoBuilder#2]
Is it possible to add a @Required annotation to define that a class member is required in the Builder constructor?

As an example, considering the following POJO:

``` java
@Builder
public class User {
  @Required
  String name;
  int age;
}
```

It will generate the following Builder class:

``` java
public final class UserBuilder {

  private final String name;
  private int age;

  private UserBuilder(final String name) {
    this.name = name
  }

  public static UserBuilder user(final String name) {
    return new UserBuilder(name);
  }

  public static UserBuilder user(final User from) {
    final UserBuilder builder = new UserBuilder(from.name);
    builder.age = from.age;
    return builder;
  }

  public UserBuilder age(final int age) {
    this.age = age;
    return this;
  }

  public User build() {
    final User user = new User();
    user.name = name;
    user.age = age;
    return user;
  }
}
```

**Comment by jenzz** [comment]
Yeah I was thinking about adding something like this as well. On the one hand, I don't like introducing another custom annotation since I would like to keep this library small and simple, but I do like the idea of this feature.

I usually prefer having a no-args constructor and doing the check in the `build` method like so:

```
public User build() {
    User user = new User();
    if (name == null) throw new IllegalStateException(name + " must not be null");
    user.name = name;
    return user;
}
```

However, this obviously doesn't enforce the parameter to be present upon Builder creation. I most probably don't have much time in the near future to implement this, but feel free to send a PR (even with WIP) and I might pick it up soon if I don't get tied up with stuff.

**Comment by jenzz** [comment]
I finally found some time to implement this.
It will be part of **v1.1**.

cc @RoRoche
